name : 'BBC Asia', url : 'https://feeds.bbci.co.uk/news/world/asia/rss.xml'
name : 'CNA', url : 'https://www.channelnewsasia.com/api/v1/rss-outbound-feed?_format=xml'
name : 'SCMP', url : 'https://www.scmp.com/rss/3/rss.xml'
name : 'Radio Free Asia', url : 'https://www.rfa.org/english/feed/rss2.xml'
name : 'The Diplomat', url : 'https://thediplomat.com/feed/'
name : 'East Asia Forum', url : 'https://eastasiaforum.org/feed/'
name : 'e27', url : 'https://e27.co/feed/'
name : 'Nikkei Asia', url : 'https://asia.nikkei.com/rss/feed/nar'
name : 'Manila Bulletin', url : 'https://mb.com.ph/rss/'
name : 'GMA News', url : 'https://data.gmanews.tv/gno/rss/news/feed.xml'
name : 'PhilStar News', url : 'https://www.philstar.com/rss/headlines'
name : 'Manila Standard', url : 'https://manilastandard.net/feed/all'
name : 'Business World', url : 'https://www.bworldonline.com/feed/'
name : 'Rappler News', url : 'https://www.rappler.com/rss'
name : 'Interaksyon TV5', url : 'https://www.interaksyon.com/feed/'
name : 'Current Ph', url : 'https://currentph.com/feed/'
name : 'Panay Island News', url : 'https://panaynews.net/feed'
